version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:${PROMETHEUS_PORT}"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:${GRAFANA_PORT}"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:${ALERTMANAGER_PORT}"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    environment:
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASS: ${GMAIL_APP_PASS}
    command: --config.file=/config/alertmanager.yml --log.level=debug
    restart: unless-stopped

  flowercare-exporter:
    image: flowercare-exporter
    build:
      context: flowercare-exporter
      dockerfile: Dockerfile
    command: --refresh-timeout=${FLOWERCARE_REFRESH_DURATION} --stale-duration=${FLOWERCARE_STALE_DURATION} ${FLOWERCARE_SENSOR_LIST}
    network_mode: host
    privileged: true
    restart: unless-stopped

volumes:
  prometheus-data: {}
  grafana-data: {}
  alertmanager-data: {}
