global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - rules/cannabis_rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - '<raspi-ip-addr>:9294'