{
 "title": "FlowerCare Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Light Supplied",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "flowercare_brightness_lux", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "flowercare_moisture_percent", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Soil temperature of the plant.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "flowercare_temperature_celsius", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Conductivity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    { "expr": "flowercare_conductivity_sm", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Sensor Battery %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "flowercare_battery_percent", "legendFormat": "{{name}}" }
   ]
  }
 ]
}